homebrew_taps:
  - buo/cask-upgrade
  - nikitabobko/tap

homebrew_cli_utils:
  - go
  - fd
  - uv
  - vim
  - fzf
  - git
  - bat
  - mas
  - mole
  - stow
  - tlrc
  - tmux
  - btop
  - httpie
  - zoxide
  - lazygit
  - ansible

homebrew_casks:
  - zed
  - zen
  - vlc
  - thaw
  - pinta
  - aldente
  - anydesk
  - calibre
  - raycast
  - spotify
  - ghostty
  - itsycal
  - homerow
  - flux-app
  - oversight
  - protonvpn
  - ente-auth
  - bitwarden
  - wispr-flow
  - app-cleaner
  - cryptomator
  - todoist-app
  - proton-mail
  - proton-drive
  - google-drive
  - logi-options+
  - betterdisplay
  - input-source-pro
  - nvidia-geforce-now
  - cold-turkey-blocker
  - font-fira-code-nerd-font

homebrew_mas_apps:
  - { name: "UpNote", id: 1398373917 }
  - { name: "Amphetamine", id: 937984704 }
  - { name: "AdGuard Mini", id: 1440147259 }

