- name: Update repos
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: software_update_all | default(false)

- name: Install CLI packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs_cli }}"
    state: present

- name: Install extra packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs_extra_apt[profile] | default([]) }}"
    state: present

- name: Clean redundant packages and dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
