- name: Install packages
  ansible.builtin.include_tasks: "{{ ansible_facts['pkg_mgr'] }}.yml"
  tags: packages

- name: Install non-distro tools
  ansible.builtin.include_tasks: bin.yml
  when: ansible_facts['pkg_mgr'] in ['apt', 'pacman']
  tags: packages

- name: Install Docker/OrbStack
  ansible.builtin.include_tasks: docker.yml
  tags: docker

- name: Install Tailscale
  ansible.builtin.include_tasks: tailscale.yml
  tags: tailscale
