- name: Update package database
  become: true
  community.general.pacman:
    update_cache: true

- name: Install CLI packages
  become: true
  community.general.pacman:
    name: "{{ pkgs_cli }}"
    state: present

- name: Install extra packages
  become: true
  community.general.pacman:
    name: "{{ pkgs_extra_pacman[profile] | default([]) }}"
    state: present

- name: Remove unneeded dependencies
  become: true
  community.general.pacman:
    autoremove: true
