- name: Configure OS
  hosts: all
  gather_facts: true
  roles:
    - role: print_facts # debug
      tags: facts      

    - role: packages
      tags: packages
      
    - role: terminal
      tags: terminal