- name: Update repos
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs_apt }}"
    state: present

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs_common }}"
    state: present

- name: Clean redundant packages and dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
