- name: Update Brew and packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ taps }}"
    state: present

- name: Install CLI utilities
  community.general.homebrew:
    name: "{{ cli_tools }}"
    state: present

- name: Install GUI applications (Casks)
  community.general.homebrew_cask:
    name: "{{ apps }}"
    state: present

- name: Install Mac App Store applications
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ mas_apps }}"
