- name: Install Docker & kubectl
  become: true
  apt:
    name:
      - docker
      - docker.io

- name: Create Docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes

