- name: Update repositories cache and upgrade packages
  become: yes
  apt:
    name: "*"
    state: latest
    # force: yes # Fixes the "Packages were downgraded and -y was used without --allow-downgrades" error
    # allow_downgrades: yes
    update_cache: yes

- name: Install packages and utilities
  become: yes
  apt:
    name:  "{{ packages_to_install }}"
    state: latest

- name: Install apt-only packages and utilities
  become: yes
  apt:
    name:  "{{ apt_packages }}"
    state: latest

- name: Clean redundant packages and dependencies
  become: yes
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

