- name: Update repos
  become: true
  apt:
    update_cache: yes

- name: Upgrade system
  become: true
  apt:
    name: "*"
    state: latest
    force: yes

- name: Install packages and utilities
  become: true
  apt:
    name:  "{{ packages_to_install }}"
    state: latest

- name: Clean redundant packages and dependencies
  become: true
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install and configure ZSH
  include_tasks: zsh.yml

- name: Install Docker and Kubectl
  include_tasks: containers.yml
