- name: Update repos
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    force: true

- name: Install packages and utilities
  become: true
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: latest

- name: Clean redundant packages and dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true

- name: Install VSCode
  ansible.builtin.include_tasks: vscode.yml

- name: Install and configure ZSH
  ansible.builtin.include_tasks: zsh.yml

- name: Install Docker and Kubectl
  ansible.builtin.include_tasks: containers.yml
