- name: Download VSCode
  ansible.builtin.get_url:
    url: '{{ vscode_url }}'
    dest: ~/Downloads/vscode.deb
    mode: 440

- name: Install VSCode
  become: true
  ansible.builtin.apt:
    deb: '{{ ansible_env.HOME }}/Downloads/vscode.deb'
