- name: Update repos
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs_server_apt }}"
    state: present

- name: Install non-distro tools
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/bin.yml"
