- name: APT minimal install
  ansible.builtin.include_tasks: apt.yml
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Pacman minimal install
  ansible.builtin.include_tasks: pacman.yml
  when: ansible_facts['pkg_mgr'] == 'pacman'

- name: Apply server hardening
  ansible.builtin.include_tasks: hardening.yml
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install Docker
  ansible.builtin.include_tasks: docker.yml
  when: ansible_facts['pkg_mgr'] == 'apt'