- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    version: "{{ dotfiles_repo_branch }}"
    remote: https
    clone: true
    update: true
    force: false

- name: Run Stow
  community.general.make:
    chdir: "{{ ansible_facts['env']['HOME'] }}/.dotfiles"
    target: all
