- name: Create ZSH cache directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.cache/zsh"
    state: directory
    mode: '700'

- name: Create ZSH history file
  ansible.builtin.copy:
    content: ""
    dest: "{{ ansible_facts['env']['HOME'] }}/.cache/zsh/history"
    force: false
    mode: '600'

- name: Make ZSH default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ '/bin/zsh' if ansible_facts['os_family'] == 'Darwin' else '/usr/bin/zsh' }}"
