- name: Install pip and Python modules
  include_tasks: pip.yml

- name: Install VSCode Settings Sync extension
  command: code --install-extension shan.code-settings-sync
  changed_when: false

- name: Setup Docker
  include_tasks: docker.yml

- name: Create temporary folder
  file:
    path: "~/ansible_temp"
    state: directory

- name: Configure Nano editor
  include_tasks: nano.yml

- name: Configure Tilix
  include_tasks: tilix.yml

- name: Configure ZSH
  include_tasks: zsh.yml

- name: Delete temporary folder
  file:
    path: "~/ansible_temp"
    state: absent
