- name: Restart dock
  ansible.builtin.command: killall Dock
  changed_when: true

- name: Restart ssh
  become: true
  ansible.builtin.systemd_service:
    name: "{{ 'sshd' if ansible_facts['os_family'] == 'Archlinux' else 'ssh' }}"
    state: restarted

- name: Reload ufw
  become: true
  ansible.builtin.command: ufw reload
  changed_when: true
  when: not ansible_check_mode
