- name: Restart dock
  ansible.builtin.command: killall Dock
  changed_when: true

- name: Reload ufw
  become: true
  ansible.builtin.command: ufw reload
  changed_when: true
  when: not ansible_check_mode
